platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.8"

inputs:
- name: sdx-pony
  path: gopath/github.com/ONSdigital/sdx-spike

run:
  path: ls gopath/github.com/ONSdigital/sdx-spike