platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.8"

inputs:
- name: sdx-pony
  path: gopath/src/github.com/ONSdigital/sdx-spike/cf-deploy

run:
  path: gopath/src/github.com/ONSdigital/sdx-spike/cf-deploy/ci/test.sh